### ISSUE TITLE
Compatibility with Boost Navigation Fumbling

### ISSUE THREAD

**Issue by argwallace** [michael-milette/moodle-filter_filtercodes#113]
I am able to use the {ifloggedin} tags when creating custom menus without an issue. However, when I try to use this with the custom menus on "Boost Navigation Fumbling", it doesn't work. I am guessing it has to do with the the BNF plugin rather than FilterCodes. However, since it is working on the custom menus, is there something I am missing in order to get this to work with the menus on the other plugin? Thanks! ~Stephen

**Comment by michael-milette** [comment]
Hi Stephen,

If you are seeing the FilterCodes instead of them being procrssed, the problem is very likely BNF. I will take a look at that plugin and see if I can track down. I suspect that it will also not support multi-language. Getting a developer to implement Moodles string filter API, for enabling multi-language, is often perceived as a greater reason to developers and  the end result is that it will end up enabling FilterCodes too.

If you want to contact the developer of BNF, ask them to apply the output functions documented at https://docs.moodle.org/dev/Output_functions

Best regards,

Michael
