### ISSUE TITLE
Example admin menu has sub-sub-menuitems

### ISSUE THREAD

**Issue by Richardvi** [michael-milette/moodle-filter_filtercodes#138]
Hi Michael,

Your example admin custom menu: https://github.com/michael-milette/moodle-filter_filtercodes/blob/master/README.md#filtercodes-in-a-custom-menu
...has sub-sub-menu items. 

I thought custom menu items could only have one layer? Mine have (Fordson)

That might be why people think that custom menus are not working (correctly)

**Comment by michael-milette** [comment]
Hi @Richardvi ,

You are correct, most Boost-based Moodle themes do not support sub-menus. But there are some that still do.

However, that is not why people say it doesn't work. I had it working properly back in Moodle 3.2 to 3.4 without any patches. Unfortunately, the Moodle API that I was using changed and was no longer compatible. So now the reason it doesn't work is because the menus requires that you either patch your theme (like Fordson) or patch Moodle - which makes it work with most themes. Learn more about this by going to https://github.com/michael-milette/moodle-filter_filtercodes#user-content-can-i-use-filtercodes-in-moodles-custom-menus . If you know of a way that I could do this without having to patch, I am open to suggestions.

If you installed Moodle using 'git clone ...', and still have the .git folder there, you can easily apply the patch using the following commands from a command prompt starting in the webroot of your Moodle site:

git remote add upstream https://github.com/michael-milette/moodle.git
git fetch upstream
git cherry-pick MDL-63219-**Mxxx**

Note: The **Mxxx** should be replaced by the version of Moodle you are using. There are patches available for Moodle M37, M38, M39 and M310. There is also a ticket open in the Moodle Tracker to have support for this feature integrated into Moodle so that it works in most themes. See https://tracker.moodle.org/browse/MDL-63219.

Wish I had better news for you. Hope this helps.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @Richardvi ,

On a side note, if you are interested in giving your custom menu a facelift, you may also be interested in https://tracker.moodle.org/browse/MDL-66856 which enables you to include HTML in custom menus.

This makes it possible to add abbr tags which could be required in order to meet accessibility guidelines. It also enables you to do things like add FontAwesome icons to your menus which, not only gives the menus a nice touch but, can make it easier for really young kids to navigate by just telling them which pictures to click on.

Again, this feature is built-into some themes but the patch makes it work in most themes.

Best regards,

Michael

**Comment by michael-milette** [comment]
Forgot to mention - I hear you @Richardvi about the examples with sub-menus. I have since created more examples without sub-menus and hope to improve and update the examples in the future. I also have other new examples for things like creating a status panel on the dashboard. I have also started creating a YouTube channel with videos demonstrating uses for FilterCodes. Unfortunately I have way more plans than I have time these days. Will leave this ticket open as a reminder to myself.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @Richardvi ,

Thanks again for reporting this issue. I removed the sub-menus as you suggested. In fact, I completely re-wrote the user, admin and developer sample menus in the documentation. The updated documentation will be included in the upcoming release of FilterCodes later this month.

Best regards,

Michael

**Comment by Richardvi** [comment]
Thanks Michael and apologies for the late respons. I still had this on my to-do list and as you see I'm now working Saturday evenings  to get some stuff of this list :)

Don't get me wrong: I would love sub-sub menu's in Boost. I would use them if I could.

And I voted for the tracker you mentioned.

I also subscribed to your YouTube channel. So now you need to make some more content :p
