### ISSUE TITLE
Custom profile field doesn't show default value unless profile updated

### ISSUE THREAD

**Issue by faraazandeh** [michael-milette/moodle-filter_filtercodes#151]
Hello dear @michael-milette,
We have a custom profile field for credit which has 0 as its default value.
& we have a custom html block using {profile_field_cr} to show users how much credit they have. You kindly updated the plugin to show values when it's 0. We recently found that when setting default value to 0 & the field is locked, it shows blank space instead of 0 unless we update the user profile once. Does it have sth to do with moodle? Or is there any way to solve the issue from this end?

Sincere Regards

**Comment by michael-milette** [comment]
Hi @faraazandeh ,

Someone else recently reported a similar issue and I think I fixed it - as long as the field actually contains a zero. Even if it has a default of 0, if it is blank, it will not display 0.

I develop enhancements and bug fixes for FilterCodes throughout the year but release the official version on Moodle.org twice a year, around the time of the next release of Moodle.

Give the version on GitHub a try. It includes the fix. If you can, leave me a note to let me know how it turned out.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @faraazandeh ,

As I have not heard back from you in the past month, I will assume that everything is working out better for you and will close this ticket. If you have anything further related to this issue, please feel free to re-open this ticket or create a new ticket.

Best regards,

Michael
