### ISSUE TITLE
Feature request: {coursesprogressbar} and {coursesprogress}

### ISSUE THREAD

**Issue by brunohcury** [michael-milette/moodle-filter_filtercodes#161]
Hello Michael,
I would like to know if there is the possibility of inserting the following filters:
{coursesprogressbar} and {coursesprogress}.
In this case, different from the existing ones, it would bring general information on the student's panel of how many courses the student has completed from a total of the courses he has enrolled.
In this case for this bar to work for a specific topic, I need to enable **"course completion"** in **mymoodle/course/completion.php**.
This general bar would be very important as it shows the overall progress of the student seeing all courses, how many steps (courses) he has completed out of a total of 100%.
Thank you very much in advance
Thank you very much

![progress](https://user-images.githubusercontent.com/25593136/127013276-7b45b14f-94c1-459c-8e3b-33f73d1b40c5.png)

**Comment by brunohcury** [comment]
Hello Michael,
Would you know if this is possible to do by filtercodes?

**Comment by michael-milette** [comment]
Hi @brunohcury ,

Thanks for the suggestion. If I created a new tag called {coursescompleted}, it would display the number of courses completed as a percentage of the total number of courses in which the student is enrolled. Then you could insert that into the new {chartprogressbar} tag that I am currently developing which will turn a number from 0 to 100 into a progress bar.

The actual name of the tags are not finalized yet but you would create the progress bar by doing something like this:

Cursos concluidas {coursescompletedpercent}%
{chartprogressbar {coursescompletedpercent}}

Would that work for you?

Michael

**Comment by brunohcury** [comment]
Hello Michael,
Thanks for your feedback.
I believe this is exactly what I need. In this case will I need to activate "course completion"?
Thank you very much

**Comment by michael-milette** [comment]
Yes.

**Comment by brunohcury** [comment]
Michael, good afternoon!
Can the "{chart progress bar 100}" tag already be used?
In this case, how do I make it work?

**Comment by michael-milette** [comment]
It is not quite finished yet but it does work. You may not be able to put other tags inside it yet. I have not tested that part yet.

To make it work, you will need to get the latest version of FilterCodes here on GitHub.

You were very close in the syntax. Just remove the space between progress and bar:

{chart progressbar 100}

Best regards,

Michael

**Comment by brunohcury** [comment]
Michael,
I did the syntax test, but it didn't work, see screenshot.
I'm on version 2.2.4.
I also enabled course completion.
Am I doing something wrong?
![progress](https://user-images.githubusercontent.com/25593136/135945393-e64069c7-384b-4b51-b38b-54734ebc9b6e.PNG)

**Comment by michael-milette** [comment]
If you didn't download FilterCodes in the last24 hours, you don't have the latest version. Try again.

**Comment by michael-milette** [comment]
Hi @brunohcury ,

Just wanted to give you an update. It is still not finished however the charts now work with static values. There is now also a new pie chart format and required title text. Here are a few examples:

{chart radial 75 Assignments completed}
{chart pie 35 Semester progress}
{chart progressbar 95 Overall completion}

The current result is:
![image](https://user-images.githubusercontent.com/3808579/145646478-158d9da2-8c7c-4d97-9b66-cf75d094c930.png)

It is still under development and will likely change more in the future. It will also become more useful once other tags can be inserted to replace the values to make it more dynamic.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @brunohcury ,

There are 3 tags now relating to course progress:

- {courseprogress}: Works pretty much as it has in the past. It will display "95% complete". It gets its string format from the block_myoverview language strings, specifically the "completepercent" string.
- {courseprogresspercent}: Simply displays the percentage as a number without any formatting or percentage symbol: "95"
- {courseprogressbar}: Displays the completion progress bar with the text below it as "Completed : 95%". The percentage number is contolled by the "percents" string in the "moodle" language strings.

You can also use {chart progressbar {courseprogresspercent} Caption to be displayed} combination which will display a similar bar to {courseprogressbar} but give you the flexibility of specifying the label to appear below the bar. Example: "Caption to be displayed: 95%". The format of the caption for {chart progressbar} is controlled by the "chartprogressbarlabel" language string.

If you want to create the caption yourself, you can omit the label and just display the progress bar by specifying a blank space instead of a label. Example: {chart progressbar {courseprogresspercent} } . If you forget the space, the tag will not work.

IMPORTANT: Please note that the {courseprogressbar} and the {chart} tags are still in ALPHA stage of development and may change in the future.

Given this flexibility, I hope that you will be able to display the information in the format you desire.

If you would be so kind, I would appreciate it very much if you would please test it out and let me know how it works out for you. These features are currently only available in the latest version of FilterCodes here on GitHub. If it works for you, I will include these changes in the upcoming release of FilterCodes on Moodle.org/plugins around the same time as the release of Moodle 4.0.

Best regards,

Michael Milette

**Comment by brunohcury** [comment]
Hello Michael,

Thank you very much for the Filter update.
Can you tell me if we can use it as shown in the print below? We will use it as the overall completion bar (from 0 to 100%) on the student dashboard indicating how many courses he has completed so far.

Thank you very much in advance

![127013276-7b45b14f-94c1-459c-8e3b-33f73d1b40c5](https://user-images.githubusercontent.com/25593136/162591381-c72d27c8-7c16-4c86-aaa3-85dd69d0f41d.png)

**Comment by michael-milette** [comment]
Hi @brunohcury 

You certainly can. However, I do not have tags for the total number of courses in which someone is enrolled nor for how many courses they have completed. You would need additional new tags.

Michael

**Comment by michael-milette** [comment]
As there has been no additional discussion regarding this issue, I am closing this ticket for now and integrating related tags as is. Please feel free to create a new issue ticket if you have any further requests.

Best regards,

Michael
