### ISSUE TITLE
Coursecards for individual courses(UI elements)

### ISSUE THREAD

**Issue by rvalero240388** [michael-milette/moodle-filter_filtercodes#187]
Hil. We'd love to know if it is possible that the filter code "coursecards id" could reference individual courses instead of top level categories.

We are interested in a setup a block in the dashboard with a selection of individual coursecards, this is not possible with the "coursecards id" because this courses belong to different categories. 

Sorry for my english :)

**Comment by rvalero240388** [comment]
Thanks, Michael. I think this will achieve our desire outcome.

**Comment by rvalero240388** [comment]
Hi, Michael.

Your solution is correct, however this will generate a duplicate enrollment record for the student. I propose, in addition to your solution, the following actions:

1. **Hide self-enrollment** in the fake course;
2. Allow, into fake course, **course:view capability** to authenticated users.
3. Ensuring that registrations are enabled in the desired course.
``
This complement to your solution proposal prevents double enrollment from being generated because the student needs to enroll in both to access.

**Comment by michael-milette** [comment]
Hi @rvalero240388 

Your welcome. Your suggestion is actually a pretty good solution. Thank you for sharing!

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @rvalero240388 and @davefoord,

You got it! The latest version of FilterCodes now includes a new {coursecard} tag that enables you to display a configurable list of course cards by specifying their course id. 

Valid examples:

- {coursecard 20} : This would display a single course card for the course with ID 20.
- {coursecard 20 43 104} : This would display three course cards for the courses with Id 2-, 43 and 104.
- {coursecard 9999} : This would not display anything unless you actually have a course that exists with an ID of 9999. This can be useful if you delete a course down the road instead of displaying an error.

Invalid examples:

- {coursecard 1} : This will not display anything since course id 1 is the site, not a course.
- {coursecard} : This will just display the tag. One or more ID parameters must be specified for the tag to be valid.
- {coursecard 1a} : This will just display the tag because course ID's can only be numbers.

If you would be so kind, I would really be thankful if you could try it out in your Moodle environment and let me know if it works for you.

Best regards,

Michael Milette

**Comment by davefoord** [comment]
Hi Michael, I thought I had replied to this last week, but cannot see my reply, so must have dreamt this!

I have tested this, and works really well - will definitely use this.
