### ISSUE TITLE
Custom course field not displayed in Home Page and Site administration

### ISSUE THREAD

**Issue by aleko21** [michael-milette/moodle-filter_filtercodes#190]
Hi, 
we successfully installed and configured filtercodes plugin to bypass the 255 char limit of the course name (we have many languages to display). 

We configured it as follows: 
- Custom field for the course with an "area text" containing the multilanguage string
- Added the {course_field_shortname} in the course title

Now the title is displayed correctly in the course home BUT in Home Page and in Site administration the coursename field is returned blank. 

How to solve this issue?

**Comment by michael-milette** [comment]
Are you using the Multi-Language Content v2 {mlang} tags instead of the version that come with Moodle? The {mlang} tags are substantially shorter than the HTML span tags leaving more room for additional languages. They are also easier to use.

If you use those instead of the FilterCodes tags in your textarea custom course field, it should display on your home page but you will need to configure this field for each course. The advantage of this solution is that it does not require any programming but it does depend on your theme displaying the custom course field. I would also suggest using a regular text field instead of a textarea as textarea field can introduce unwanted rich text HTML tags.

Other possibilities which require some programming skills which may help you achieve your desired outcome include:

- Try the excellent Generico plugin. It is made to display information based on a template.
- Creating a custom plugin.
- Patch your theme.
- Patch Moodle.

These solutions are listed from most sustainable to least sustainable.

Hope you find something useful in  these suggestions.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
As there has been no further discussion for over a month, I am closing this issue as it is a limitation of Moodle's filter functionality and there isn't much I can do about it without changing Moodle core. If you wish to re-open this issue in the future, let me know.

Best regards,

Michael
