### ISSUE TITLE
dont work with BBB & database template

### ISSUE THREAD

**Issue by jmd87fr** [michael-milette/moodle-filter_filtercodes#194]
Hi,
 I have a trouble with 2 activities : 
1) BigBlueButon filtercode don't work in the  description 
2) also dont work in the database activitie templates :-(
I tested in label: it's ok it's work good

Please do you have any idea ?  

Moodle 3.11
Filtercode 2.2.0 2021052200

**Comment by michael-milette** [comment]
Hi @jmd87fr, 

1. Do you mean FilterCodes don't work in the description field within BBB? If so, you will need to contact the author if BBB and ask them to fix their plugin so that it processed information displayed through Moodle filters.

2. Same for the Database activity.

Typically, if it works in one block or activity, it should work in others as long as the developer of the plugin programmed it correctly. It might be helpful if you point them to the Moodle Output API documentation, specifically the format_text() and format_string() functions.

Best regards,

Michael


Best regards,

Michael

FilterCodes are applied by Moodle and plugins.

**Comment by jmd87fr** [comment]
Hi Michael
Thank you for your quick answer :-) 
I understand for BBB it's not a core module. BUT for the database ?

**Comment by jb-fol** [comment]
@jmd87fr @michael-milette - Database activity templates do not process filters. There a long outstanding tracker issue at https://tracker.moodle.org/browse/MDL-58680
