### ISSUE TITLE
Feature request: Enable/disable filter codes

### ISSUE THREAD

**Issue by bozicm** [michael-milette/moodle-filter_filtercodes#227]
I would like to disable certain filtercodes from being used (disclosing system information or for performance reasons).

A management system like Atto toolbar config could be used for reference how to manage filtercodes:

![slika](https://user-images.githubusercontent.com/1941043/189082565-c2244e6e-f547-4ab9-a3c8-101f80a8b604.png)

**Comment by michael-milette** [comment]
Hi @a-kempka ,

Thank you for expressing your concerns. It is unfortunate that student-entered information is now processed through Moodle filters. That was not always the case.

As your main concern seems to revolve around the Forum activity, may I suggest that you simply disable the FilterCodes filter for that particular activity? In fact, you can do this for most instances of most activity types in a course.

As for sesskey, it really isn't a secret. There are several links that a user has access to which include the sesskey. It is even available in JavaScript. If someone really wants to make use of it, it is available to them in other ways. IP address? It is going to display your own IP address, not the one of the person who entered it. There are probably dozens of websites like www.myipaddress.com where you can go to find that out, not to mention the OS's shell/command prompt/terminal.

My concern with making it possible to disable some tags is that I want to enable people to use these tags and be creative, not frustrate them because something the documentation says should work does not. 

Hope you find this information helpful.

Best regards,

Michael Milette

[PS. Have you ever heard of the Word Censorship plugin for Moodle? Darn, I've said too much already.]

**Comment by skodak** [comment]
hi @a-kempka,

all your security concerns are valid, there are multiple security and privacy problems in this plugin.

See #246 for the details whey {sesskey} must be removed from this plugin. I am going to report more security and privacy problems later, if necessary I'll create exploit examples to persuade @michael-milette the problems are real.

**Comment by michael-milette** [comment]
Hi @a-kempka ,

Just wanted to let you know that some of your concerns have been addressed in the latest version of FilterCodes released on Moodle.org, particularly with the {sesskey} tag. A solution for some of your additional concerns is under development and will be addressed in the future. Have you had a chance to look into the Word Censorship plugin?
