### ISSUE TITLE
Make the lang tag support Moodle's multilang filter 

### ISSUE THREAD

**Issue by wilenius** [michael-milette/moodle-filter_filtercodes#266]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [X] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

As a teacher, I want to have an easier way to create multi-language content in Moodle. If the langx-tag would add the property class="multilang" to the language span tag, then the created tags would be compatible with the Multi-language content filter, which hides the span tags that do not match the selected language of the user. For more info on Multi-language content filter, see https://docs.moodle.org/402/en/Multi-language_content_filter.

### Planning on submitting a solution in a pull request (PR)?

Maybe

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hello @wilenius ,

The purpose of this tag is not to filter content based on language but to insert text that is in a different language than the page text. For example, if I am viewing a page written in English but want to insert a French or Spanish word, you would wrap the text in a set of {langx}{/langx} tags and specify the language of that text so that screen reader can read it correctly.

If you are looking for a plain text alternative to the multilang span tags, a new tag might be in order. Alternatively, you could use the multilang2 filter with its {mlang XX}{mlang} plain text tags.

Let me know what you think about this.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
Hi @wilenius ,

You asked for it, you got it! I just added a set of {multilang xx}...{/multilang} tags to FilterCodes. All it does is convert:

    {multilang xx}...{/multilang}
to
    <span lang="xx" class="multilang">...</span>

It therefore depends on Moodle's Multi-Language Content filter being enabled and positioned below FilterCodes in Filter Management so that it then processes its tags.

Please note that this feature is currently only available in the version of FilterCodes available here on GitHub. I would appreciate it very much if you would be so kind as to try it out and get back to me to let me know if it works for you.

If it works for you, this feature will be included in the upcoming release of FilterCodes on Moodle.org within the next few weeks.

Best regards,

Michael

**Comment by wilenius** [comment]
Brilliant! Let me test it on our development server and get back to you.

And re the original lang tag functionality, makes complete sense, and a handy feature too.

**Comment by wilenius** [comment]
Just gave it a go, and it works nicely. One can add multiple paragraphs of multilang content too, as long as the multilang tags are back-to-back, e.g.:

{multilang fi}Finnish
<h5>heading</h5>{/multilang}{multilang en}english
<h5>heading</h5>
{/multilang}{multilang sv}swedish
<p>paragraph</p>
{/multilang}

So it works just like the span tags, but they are much easier for the users.

**Comment by michael-milette** [comment]
Hi @wilenius ,

Thanks for the suggestion and the feedback. I really appreciate you testing it.

Best regards,

Michael
