### ISSUE TITLE
Bug: Not displaying FilterCodes tags in side navigation

### ISSUE THREAD

**Issue by bfriesenvcc** [michael-milette/moodle-filter_filtercodes#267]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [X] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

In Moodle 4.1, Filtercodes are not displaying as intended on the Course index, when included in a Text and Media resource (previously called label).

### What do you think should have happened?

I expected the name ("Blair" in this case) to show on the course index.

### Steps to reproduce

1. Login as some with editing access to a course
2. Go to the course and add a Text and Media resource to any section of the course.
3. Include a filtercode, such as firstname in the first few words of the T&MR and save the change.
4. Open the course index and see how the label appears on the index.
5. See how it appears as the filtercode and not what the filtercode should be showing.

### Screenshots

![filtercodes in course index](https://github.com/michael-milette/moodle-filter_filtercodes/assets/8193384/7a70b38e-8a1b-4034-a115-672e9ac4b2d7)

### Moodle version

 4.1.5 (2022112805)

### Installed Moodle UI Language packs.

- [X] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### System information

Client Device type: (e.g. Desktop, iPhone or iPad, Android phone or tablet, Other - specify)
Client Operating System: (e.g. Windows, Linux, Mac OS, Android, iOS, Other - specify)
Client Web Browser: (e.g. Chrome, Edge, Firefox, Safari, Safe Exam Browser, Moodle Mobile App)
Server Operating System: (e.g. Windows, Linux, Mac OS, Other - specify)
Server Webserver: (e.g. Apache, Nginx, IIS, Other - specify)
Server PHP: (e.g. 7.3, 7.4, 8.x, Other - specify)

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @bfriesenvcc ,

I tested this out using Moodle 4.1 (original release) and Moodle 4.0.5+ (2022112805.08) and it works fine in both when using the Boost theme.

<img width="320" alt="image" src="https://github.com/michael-milette/moodle-filter_filtercodes/assets/3808579/45036ab4-e669-4984-893c-43e5c8343861">
<img width="320" alt="image" src="https://github.com/michael-milette/moodle-filter_filtercodes/assets/3808579/84203edc-d1d5-4919-b5bc-7e9ff20f2927">

There were actually a number of problems with the side navigation in earlier versions of Moodle 4.0 related to this and language switching but these have since been fixed.

If this is still a problem for you in recent releases of Moodle 4.1, I am pretty confident in saying that the problem is with the theme you are using. If the side navigation in your theme is based on early code from Moodle 4.0, it still contains the bug. I recommend that you contact the developer of your theme and ask them to fix it.

Alternatively, if it works like Moodle's Boost theme, labels don't show up in the navigation when Editing is turned off so it may be something you can live with.

Best regards,

Michael Milette

**Comment by bfriesenvcc** [comment]
Hmmm... we are using Boost. My apologies. I will have to investigate on our end. Good tip about the editing mode, though. 

As always, thank you for your very valuable time, and this amazing plugin.
