### ISSUE TITLE
Coursename

### ISSUE THREAD

**Issue by behoof** [michael-milette/moodle-filter_filtercodes#27]
Hi,
Excellent plugin! 
I want to use the filter for the course full name (on a course page). Do you have a variable for it?

Bert

**Comment by michael-milette** [comment]
Hi Bert,

Thank you for taking the time to ask your question regarding the FilterCodes plugin for Moodle. I am delighted to hear from you.

You won't believe your luck but, as it turns out, I just happen to have added a {coursename} tag about 9 days ago. It is currently only available here on GitHub and will be released on Moodle.org about a couple of weeks just in time for the upcoming release of Moodle 3.4.

A couple of notes:

1. If you try to use the tag outside a course, it will return the site's fullname instead.
2. If you are running a multilingual site, be sure to place the FilterCodes plugin higher in the list so that the multilingual filter processes your site name after FilterCodes has inserted the information.

Please feel free to download the new plugin from GitHub, give it a try and share your experience back with me. Although I do quite a bit of QA testing on my plugins, I always welcome feedback from members of the Moodle community.

Best regards,

Michael Milette
