### ISSUE TITLE
Bug: First video on page is gone after "FilterCodes" in ON globally

### ISSUE THREAD

**Issue by caiadogithub** [michael-milette/moodle-filter_filtercodes#283]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [X] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

When "FilterCodes" is ON globally, first video is not visible

![ON](https://github.com/michael-milette/moodle-filter_filtercodes/assets/23316275/fa3af5c5-a52c-46e4-b27d-0706789beb44)

### What do you think should have happened?

I expected all videos on page to be visible when "FilterCodes" is ON globally

![OFF](https://github.com/michael-milette/moodle-filter_filtercodes/assets/23316275/42731ab8-b200-4652-af2e-b84365d61e6a)

### Steps to reproduce

1. Login as 'admin'
2. Go to '/admin/filters.php'
3. Click on 'Filter Codes' and enable it.
4. Access any page with more than one YouTube URL
5. See error or issue.

![ON](https://github.com/michael-milette/moodle-filter_filtercodes/assets/23316275/16307743-0270-4303-b0e0-e4c018803261)

### Moodle version

Moodle 3.11.16+

### Installed Moodle UI Language packs.

- [ ] English only
- [X] One or more other languages/regional dialects (specify below)
- [ ] Other

### If other language(s), please specify

EN, PT-BR

### Workaround

No.

### System information

Client Device type: Desktop
Client Operating System: Ubuntu, Windows
Client Web Browser: Chrome, Edge, Firefox
Server Operating System: Ubuntu
Server Webserver: Apache2
Server PHP: 7.4

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @caiadogithub ,

I tested on both Moodle 3.11 and 4.0.3 but I could not reproduce the issue you described.

<img width="320" alt="image" src="https://github.com/michael-milette/moodle-filter_filtercodes/assets/3808579/bd20a359-ce22-4739-b8f1-0dc5e241949a">

Could you share the HTML that you are using?

Best regards,

Michael

**Comment by caiadogithub** [comment]
Hi, @michael-milette 

Here are the HTML codes from the pages where the first video is gone:

![Firefox_Screenshot_2023-12-12T13-19-45 929Z](https://github.com/michael-milette/moodle-filter_filtercodes/assets/23316275/05d5c34d-d5b9-4f18-8189-9fd0f3f4f3f5)

![Firefox_Screenshot_2023-12-12T13-20-01 592Z](https://github.com/michael-milette/moodle-filter_filtercodes/assets/23316275/ef573bf9-6cf4-4120-9fb4-c20632407ca0)

Ricardo
``

**Comment by michael-milette** [comment]
Hi @caiadogithub ,

I typed in your exact HTML code into Moodle 3.11 course Labels.
<img width="400" alt="image" src="https://github.com/michael-milette/moodle-filter_filtercodes/assets/3808579/7ac35996-db19-46bc-9b3e-e67364c37ad1">

Works fine for me, with FilterCodes enabled and disabled.

The only thing I can suggest is that you go to Site Administrator > Plugins > Manage Filters and make sure that FilterCodes is at the top of the list of filters.

There is nothing in the HTML that you provided that would cause FilterCodes to have any effect on it. FilterCodes checks the content of the field for the occurence of a "{" character. If it doesn't find one, it does not process anything in the field. That said, if you are using FilterCodes elsewhere in the page, it could potentially affect it.

You could also try set debugging to DEVELOPER mode and check the box to show errors. This might reveal if there is a coding issue.

Unfortunately, based on the limited information that you have shared, I am not seeing the issue. Although the issue only appears when you enable FilterCodes, it could be a conflict with another plugin you have installed. The problem is, if I cannot reproduce the issue, I cannot fix it for you.

If you would like to consider premium support, I would be happy to troubleshoot your issue further by connecting to your website to determine what is going on. Just contact me through my website at https://www.tngconsulting.ca/contact.

Best regards,

Michael

**Comment by caiadogithub** [comment]
@michael-milette 

"_The only thing I can suggest is that you go to Site Administrator > Plugins > Manage Filters and make sure that FilterCodes is at the top of the list of filters._"

It works now!!

Thanks!

Ricardo

**Comment by michael-milette** [comment]
HI @caiadogithub ,

Glad you got it working. Thanks for sharing the solution.

Best regards,

Michael Milette
