### ISSUE TITLE
Feature Request: ifcourse_field_shortname contains

### ISSUE THREAD

**Issue by jb-fol** [michael-milette/moodle-filter_filtercodes#285]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [X] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

As a user, I can see relevant content from custom course fields if the data exists. 

Same functionality already exists for user profile fields with ifprofile_field_shortname

### Planning on submitting a solution in a pull request (PR)?

No

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @jb-fol ,

The tags you may be looking for are:

{course_fields}: Displays the custom course fields.

{course_field_shortname} : Displays custom course field. Replace "shortname" with the short name of a custom course field all in lowercase.

NOTE: Respects a custom course field's Visible To setting.

If this is not what you need, please feel free to reopen this ticket.

Best regards,

Michael Milette

**Comment by jb-fol** [comment]
Thanks Michael - I’m successfully using course_field_shortname

What I was asking for was the same as in issue #84 which only shows the content if the profile field is populated.

**Comment by michael-milette** [comment]
Hi @jb-fol ,

Sorry for the misunderstanding. Please simply add a comment to #84 and you will be automatically notified when I make progress on that ticket.

Best regards,

Michael

**Comment by acquaalta** [comment]
Hi @michael-milette,
Thanks again for your wonderful plugin and all the other contributions that you make to the Moodle community :-)

Let's say I want to display the following text in a label in a course:

Fruit: {course_field_fruit} 

This is of course a "course_field_shortname" tag.
And I know that if the relevant course field in that course is empty, nothing will be shown, and if it has content, it would be displayed. The thing is that in any case the preceding "Fruit: " text would be displayed to the user, and it would be strange since if there is not content to show, there would be a "Fruit: " text without something to follow it.

Is there any creative solution that you can think about, that would help us in this kind of scenario?

**Comment by michael-milette** [comment]
Hi @acquaalta ,

I've had to deal with that too. What I did in the past was to give the course field a default value like (not set yet), (to be completed) or (none).

Beyond that, we would need a new ifempty or something like that.

Best regards,

Michael
