### ISSUE TITLE
Bug: YouTube video turns into a black rectangle next to the {details} tag

### ISSUE THREAD

**Issue by VadimLjovkin** [michael-milette/moodle-filter_filtercodes#290]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [X] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

Thank you for the wonderful plugin! If I use the {details} tag next to a YouTube video link, the video cover turns into a black rectangle and stops being active (clicking on the video does not cause the video to play).
This has always worked, but in a recent update, the video stopped displaying and turned into a black rectangle. However, if multiple videos are posted in a row, only the first one turns into a black rectangle. The others display fine, even if the {details} tag is used next to them.

### What do you think should have happened?

This has always worked, but in a recent update, the videos stopped displaying and turned into a black rectangle. 

### Steps to reproduce

1. On the course homepage, create a topic and when editing it, hide some of the text used in the {details} tag. After this tag place an active link to the YouTube video. Usually the YouTube link turns into the cover of the active video.
2. Duplicate the topic to get a full copy.
3. Refresh the page (F5) to see that the video from the top topic is displayed as an inactive black rectangle, while the video from the bottom topic is displayed correctly - the cover art is visible and you can view the video. This situation I have captured in the screenshot.

### Screenshots

![YouTube videos stop displaying](https://github.com/michael-milette/moodle-filter_filtercodes/assets/55759341/c982ded7-82ef-4058-a981-bfd9575315e1)

### Moodle version

4.3.1+ (Build: 20231215) 

### Installed Moodle UI Language packs.

- [ ] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### If other language(s), please specify

Russian

### Workaround

If you place one opening {details} or one closing {/details} tag higher on the page, the video below will be displayed correctly. It won't work if you place such a tag below, after the video.

### Additional information

I don't use other plugins, but disabling this plugin makes YouTube videos display correctly.

Sorry for bad English, I use a translator.

### System information

Client Device type: Desktop
Client Operating System: Windows
Client Web Browser: Firefox, Google Chrome, Edge.

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @VadimLjovkin ,

I am not sure that this is related to FilterCodes. I recently experienced the same issue in Moodle 4.3.2+ when inserting YouTube videos. I was not using FilterCodes in that situation. I eventually got it to work properly by removing all other HTML content on the same line as the video including leading and trailing spaces.

I will try your steps to reproduce it and see if I can determine what might be going on.

Best regards,

Michael

**Comment by aindril** [comment]
Hi Michael!
First thank you for this wonderful plugin. I am exploring this to add more personalization for our students on our Moodle site.
I am facing a major challange that I have tested on moodle 3.9 and 4.1, that as soon as I enable this plugin, all youtube embedded videos obn our moodle site stop working and it becomes a small black box.
However, as soon as I disable the filtercode plugin it starts working again.
Please help! keeping both would be critical for us.

Regards,
Aindril

**Comment by michael-milette** [comment]
Hi @aindril ,

I am not sure what is going on with your site. Moodle 4.3 with the latest version of FilterCodes here on GitHub does not seem to have the same problems. 

Here are some screenshots I just took:

<img width="378" alt="image" src="https://github.com/michael-milette/moodle-filter_filtercodes/assets/3808579/9b68759f-3402-4f89-a371-ccc1f4ee7e3b">

<img width="240" alt="image" src="https://github.com/michael-milette/moodle-filter_filtercodes/assets/3808579/9331897b-187f-49e3-9141-9e9258539882"><img width="240" alt="image" src="https://github.com/michael-milette/moodle-filter_filtercodes/assets/3808579/9e4bb488-d52c-4576-948b-97bcda7ceb62">

To help you fix your issue, I need to either be on your system to do the diagnostic or I need to be able to reproduce the issue. I suggest that you try:

1. Using the boost theme.
2. The latest version of FilterCodes here on GitHub.
3. Checking the troubleshooting tips in the README.md file that came with your plugin, especially the part about making sure that FilterCodes is moved up to the top of the list of filters and that it is enabled for both content and headings.

If none of these steps help you, let me know and I will put together a Moodle 3.9 site (mine doesn't currently work since I upgraded to PHP 8.x for Moodle 4.3).

As for the OpenAI Chat block, again, I am using the latest 2.0.1 in Moodle 4.3 with all the FilterCodes listed in the article and it is working fine for me. Could you make sure that you are using a recent release of the OpenAI Chat Block? Support for Moodle filters was only added a few months ago.

<img width="145" alt="image" src="https://github.com/michael-milette/moodle-filter_filtercodes/assets/3808579/9d53521b-69cb-4c7d-beb2-a8d3d414fcdd">

Let me know how your troubleshooting goes.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @VadimLjovkin ,

Unfortunately, I could not reproduce the issue that you are experiencing. I had no trouble putting the set of details/summary tags above and below the video.

<img width="367" alt="image" src="https://github.com/michael-milette/moodle-filter_filtercodes/assets/3808579/c62500a6-730b-497c-a869-850b8305a3bc">

<img width="343" alt="image" src="https://github.com/michael-milette/moodle-filter_filtercodes/assets/3808579/f2b11b13-d8c9-4217-a927-d92221b88d84">

<img width="365" alt="image" src="https://github.com/michael-milette/moodle-filter_filtercodes/assets/3808579/fc17fe2c-ea20-4480-a484-c7fbac078633">

It works! My suggestion would be to view the HTML source code and make sure that there is no unexpected HTML tags that ended up inside the FilterCodes tags.

If that doesn't help, try the latest version of FilterCodes here on GitHub. There was a bug a year or two ago with the way tags were being rendered but that has long since been fixed.

Hope you find this information useful.

Best regards,

Michael

**Comment by aindril** [comment]
Hi @michael-milette ,

Thanks for the inputs. I will troubleshoot as per the steps provided. Following is a sample code of how we embed the youtube video on the LMS inside a "Page" .

<h5 style="text-align: center;"><b><i><u>E-Tutorial</u></i></b></h5>
<p><b><i><u>&nbsp;<video width="850" height="650" controls="true">
                    <source src="https://youtu.be/A01DoFvrJNU">https://youtu.be/A01DoFvrJNU
                </video>&nbsp;<br></u></i></b></p>
Can you please see if this can be used to replicate the issue at your end.

Regards,
Aindril

**Comment by VadimLjovkin** [comment]
@michael-milette 
Прошу прощения! Я упустил необходимость переместить FilterCodes в начало списка фильтров!
Я сделал это и теперь видео с Ютуб отображается как нужно!
Большое спасибо вам за ваш полезный плагин и терпение к пользователям!!!
Простите, моя ошибка отняла у вас время. Желаю вам здоровья, а вашему плагину дальнейшего развития!

**Comment by michael-milette** [comment]
You're welcome @VadimLjovkin . Glad you figured out the solution.

Best regards,

Michael

**Comment by aindril** [comment]
Hi @michael-milette ,
Thanks for your help. It looks like some issue with my Moodle JS Player. When I am using the original Youtube embed code that calls the youtube player, it works:

"<iframe width="560" height="315" src="https://www.youtube.com/embed/A01DoFvrJNU?si=XxIMgwxGoKDmE6tM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> "

Now I will try and test the OpenAI plugin as well and see what is going wrong there. It could be the version issue that does not support filtercodes.

Thanks. I will keep you posted.

Regards,
Aindril
