### ISSUE TITLE
Performance: Do not call preg_replace()'s if not needed

### ISSUE THREAD

**Issue by mudrd8mz** [michael-milette/moodle-filter_filtercodes#4]
Regular expressions are expensive performance-wise. It is recommended to perform a quick precheck via `strpos()` to see if there is a substring that a filter makes use of. In your case, at the beginning of the `filter()` method, you should use `strpos()` (which is quick) to see if there is a curly bracket in the submitted text. If not, return early without spending time on all those regexp's.

See https://github.com/moodle/moodle/blob/v3.3.1/filter/tidy/filter.php#L57-L59 as an example.

**Comment by mudrd8mz** [comment]
In fact, given the amount of replacements, you could even benefit from additional scans like `{if`.

Alternatively, it seems that it would be best (from performance perspective) to use `filter_phrases()` given the list of `filterobject` instances and perform these removals in a bulk - see the `censor` filter for example.

**Comment by michael-milette** [comment]
Hi @mudrd8mz ,

After reading through the source code for filter_phrases, I decided to go with the two if "{" and if "{if") checks as well as stripos() checks across the board instead of the filter_phrases(). I do appreciate the suggestion through for this last one as I had not previously had an opportunity to explore that particular function.

You will also be happy to hear that I've reduced the script down to a single call to preg_replace().

Thank you again for taking time to share your suggestions. These changes are now included in the repo.

Best regards,

Michael
