### ISSUE TITLE
Filtercode is not working in Custom (Flat-Sidebar) Navigation Menu Plugin

### ISSUE THREAD

**Issue by josephfranciskumar** [michael-milette/moodle-filter_filtercodes#67]
Hi Michael,

Thanks for this plugin..! Its too good..! I have tried this plugin for customized menu for custom users like admin, teacher..etc i have used moove theme. Moodle 3.5 (current version). i have used this into custom navigation menu plugin for side menus. But its not working in that. But Its working in user menu in the same theme from theme settings. I have attached screenshot..! Please check it..!!! Thanks !!
![capture](https://user-images.githubusercontent.com/42690983/46610494-87117a00-cb28-11e8-83cc-afb47f69a9e5.PNG)

**Comment by michael-milette** [comment]
Hi @josephfranciskumar,

This is a known issue. I am trying to have support for this functionality built into the core Moodle Boost base theme. I was hoping to have this resolved in Moodle 3.6 but it doesn't seem to be happening. Hopefully it will by Moodle 3.7.
https://tracker.moodle.org/browse/MDL-63219

There are a couple of potential solutions:

**Option 1**
Add the following code to the Boost or Moove theme. The fix was tested on Boost theme but has not been tested on the Moove theme:
https://github.com/michael-milette/moodle-filter_filtercodes#for-themes-based-on-boost

Note that any customizations to you theme may be overwritten the next time you update Moodle and/or the Moove theme.

**Option 2**
You can give the upcoming version of FilterCodes a try. It will include partial experimental support for FilterCodes in custom menus. However, you will need to enable it in the new FilterCodes settings and, it will not work on the the Moodle Theme Settings page. This update should hopefully be available within the next couple of weeks and will be supported in Moodle 3.2+.

If you are interested in option #2, let me know and I will notify you as soon as it is available here on GitHub. I would be interested in hearing if it works for you.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
The new version of FilterCodes is now available on Moodle.org. Hope it solves your problem.
