### ISSUE TITLE
links as settings of theme

### ISSUE THREAD

**Issue by jharej** [michael-milette/moodle-filter_filtercodes#7]
Hi, 

I've tried to use this filter plugin. I've inserted link /report/progress/index.php?course={courseid} in a theme handlebar (links that apear in popup - /admin/settings.php?section=themesettinghandlebar). I realized, that {courseid} doesn't convert to real courseid. I guess theme code gets processed before filters are applied.

bye

**Comment by michael-milette** [comment]
Hi @jharej,

Thank you for your feedback. I appreciate that you took the time to write.

Actually the {courseid} tag does get converted to the real course ID for the current page. I implemented it for the exact purpose you mentioned in your example (...?course={courseid}).

If {courseid} isn't being converted into a number, I suspect that it isn't working for you due to one of two reasons:

1. You haven't installed AND enabled the filter. You can easily test this by adding a tag, like {firstname} to any page in Moodle and checking to see if it gets converted into your name.

2. The theme is not processing strings through the format_string() or format_text() functions. You will need to ask the maintainer of the Handlebar theme, Richard Oelmann, to apply one of these functions in his theme's code so that strings are processed though Moodle filters. Once he adds these functions, it will not only help you but but will also enable the theme to support multiple languages. Of course since it is open source, you can modify the theme code yourself to enable this functionality.

If, on the other hand, it is being converted into a number which isn't the course ID, please let me know and I will look into fixing it as soon as possible.

Let me know how you make out.

Best regards,

    Michael

**Comment by jharej** [comment]
Hi - if I put the link in a textfield, for example label, it works. So it must be the theme. I will contact the author of the theme. 

Thanks, 

Janko
