### ISSUE TITLE
Feature Request: Custom Profile Fields

### ISSUE THREAD

**Issue by scotthardwick** [michael-milette/moodle-filter_filtercodes#72]
Great plugin!!

Please add the ability to utilize custom profile fields added to the Moodle system as {filters}

Thanks!

**Comment by michael-milette** [comment]
Hi @scotthardwick ,

Thanks for the excellent suggestion. I think it would be useful however there could be some security implications. For example, some instances of Moodle have hidden fields that nobody is ever supposed to see. This feature would enable teachers to insert a filtercode in their content and access to these hidden fields.

Any suggestions on how this could be managed? I am thinking perhaps a Filtercode setting that would enable administrators to specify a list of the custom fields that could be processed.

Thoughts?

Michael

**Comment by scotthardwick** [comment]
That is an excellent point.  I guess incorrectly I keep looking at this as a tool to help me as the administrator add things, but with it enabled, there is nothing to stop the faculty or the students from adding in the filter codes.

I think your idea of allowing an administrator to set what filter codes are available is indeed probably the way to go.  Even for the {idnumber} filter code you just added for me, I could see some admins not wanting their users to have access to that.

Also on the topic of custom fields, the 3.7 release of Moodle is finally adding custom fields for courses, so I am sure you will be getting a request to add the ability to include filter codes for those custom fields as well. (And similarly, there are probably some that admins won't want used in a filter).

**Comment by michael-milette** [comment]
I am not too concerned about the {idnumber} tag. This is a core Moodle field which can only be hidden using CSS in a user's profile unless you actually go and modify the Moodle source code. If someone doesn't want people to know their own ID Number, they should really be using some other field. If one day, a feature is added to Moodle core to be able to enable (show) or disable (hide) some of these fields, I will apply the same to the FilterCodes.

It would be a nice feature to have. There are so many fields in a person's profile that most people don't want to capture these days due to privacy concerns. Personally, I think that there should be a minimal set of profile fields and all other fields be custom fields that people can add on their own. It would make so much more sense and they are more configurable. Unfortunately we still need to maintain backwards compatibility. Maybe that will change one day.

Good to know about custom fields for courses. I was not aware. Thanks! :-)

**Comment by thornedu** [comment]
Certainly if user_info_field.visible = 2 (Everyone) then that is okay to us, since anyone can see it anyway. If it is 0 (None), then do not allow it to be used.

The issue comes when the setting is 1 (Visible to user). In most cases I think the use of the filter would only be visible to the user since they are seeing the screen or getting email, etc. But I bet someone can think of cases where, for instance, a teacher might be able to see that data.

So, if you default allowing only profile fields set to 2 then that is safest. Perhaps allow admins to have a setting allowing use of 1. Maybe.

Also, it would be helpful if the syntax for this could be the same as the standard for user upload files, eg. {profile_field_shortname}

**Comment by michael-milette** [comment]
Hi @scotthardwick and @thornedu,

You asked for it and you got it! The latest version of FilterCodes on GitHub now includes the ability to display custom profile fields, as long as they are not set to "Not visible".

The documented syntax is as you suggested: {profile_field_shortname} (replace shortname with the actual shortname - but only in lowercase!)

Please download and try it out from GitHub for now and let me know what you think. Assuming everything goes well, the new feature will be included when I publish it in the Moodle.org plugin repository a few days before the launch of Moodle 3.8 next month.

Best regards,

Michael

**Comment by michael-milette** [comment]
@thornedu,

Thank you for your excellent suggestions regarding implementing a filter for custom profile fields in FilterCodes. I implemented almost all of them.

With regards to your comment about Visible to User vs Visible to Everyone, I am not too concerned that the teacher be able to see the data if set to Visible to User. FilterCodes fields are rendered dynamically and will only show the users own data. In order for a teacher to see someone else's data, they would need to use login as the user in which case there is no hiding any profile information that the user could see themselves. 

If this is still a concern, please share a user story describing a situation where it might be a problem.

Best regards,

Michael

**Comment by scotthardwick** [comment]
@michael-milette  Much thanks from me to you! You are fantastic!
