### ISSUE TITLE
filtercodes  conflitcts with simplecertificate plugin

### ISSUE THREAD

**Issue by bozoh** [michael-milette/moodle-filter_filtercodes#8]
Hello
This filters plugins  uses the same text tags, {username}, of an older plugin,  the simple certificate plugin 
https://moodle.org/plugins/view.php?plugin=mod_simplecertificate

And the tag
{username}   is conflicting,  since in simple certificate plugin means full user name, and in yours the user login

I suggests to change the yours text tag to something like [username] or (username) or  \username\ or {{username}} since simple certificate is an older pluging and more popular too (of course, it's more older ... )
And nice idea  for a plugin !

**Comment by michael-milette** [comment]
Hi @bozoh,

Thank you very much for your feedback and the compliment. I always love hearing from people in the Moodle community, especially other plugin developers who have had such an important impact in the Moodle world through their contributions over the years. 

Just like [ ] are used consistently for most WordPress Shortcodes, the { } braces were chosen for this Moodle project in order to be consistent with other Moodle filters which use the same delimiters. For example:

- https://moodle.org/plugins/filter_multilang2
- https://moodle.org/plugins/filter_multilangsecond
- https://moodle.org/plugins/filter_generico
- https://moodle.org/plugins/filter_tabs
- https://moodle.org/plugins/filter_collapsible

Not only does the use of { } further promote the consistency and intuitiveness for users who type these variables, is also far less likely to occur in day to day text than [ ] making it a better choice for filters.

As I said, in the world of WordPress, [Shortcode] brackets are the norm. Moodle's problem, when it comes to filters, is that it lacks a standard for filter variable delimiters. It would also be nice if there was an API so that plugins like yours can create filter codes that are limited to the scope of the plugin. Yet another option might be to have private filter code delimiters be different than global filter code delimiters. Regardless, this is probably a discussion for a different thread.

The FilterCodes plugin is working according to design and Moodle API specifications for filter operation. 

I understand that {username} is conflicting with your Simple Certificate plugin (a fine plugin I have often used on many projects by the way). By no means would I ever suggest that you change even one tag, like {username}, in order to avoid conflicts with other plugins. As you pointed out, your Simple Certificate has been around for a good while and such a change would have a major impact on all those who uses it.

With that said, I do believe that there is a solution that would enable Simple Certificate to co-exist peacefully with all filter plugins. It may even provide you with an opportunity to potentially reduce the number of calls made to format_text() and/or format_string() thereby reducing load and improving performance of your plugin.

In order to avoid conflicts with this and potentially other existing and future filter plugins, you might want to consider perhaps process your Simple Certificate {tags} first. This would eliminate them from the strings and would no longer be potentially affected by processing through Moodle filters. The simple reversal of the order in which you filter the tags will provide you the power to override any conflicts with Moodle filters.

The only drawback will be that Simple Certificate will processes its {username} tag first and the FilterCodes {username} will just not be available in Simple Certificate... something I can certainly live with and you won't ever need to worry about it again in the future. A fair compromise, wouldn't you say?

Best regards,

Michael
