### ISSUE TITLE
Bug: Scrape URL returning complete page even if passing a class or ID

### ISSUE THREAD

**Issue by ValerieMichaud** [michael-milette/moodle-filter_filtercodes#83]
I'm trying to get a specific piece of content using the scrape function:

{scrape url="wwroot/mod/assign/view.php?id=32" tag="div" class="mthy-overview" code=""} 
{scrape url="wwroot/mod/assign/view.php?id=32" tag="div" id="intro" code=""} 

No matter what I use as class or ID, even with or without the "." or "#", it always return the complete HTML page, from the <head> tag.

**Comment by michael-milette** [comment]
Hi Valerie,

Thank you for taking the time to report this issue. Upon closer inspection of what is being returned, you may notice that it is actually returning the login page and not the assignment page. This is because it is the not-logged-in web server retrieving the content of the page and not your logged-in web browser.

The SCRAPE tag can only retrieve content that is publicly available. I am not sure how to make the server think it is actually your web browser retrieving the content of the page..

Although it doesn't help you achieve what you are trying to accomplish, I hope this helps clarify what is going on for you.

Best regards,

Michael

**Comment by michael-milette** [comment]
A couple more things...

If the parser is unable to figure find the content you specified using the tag, class and id, the default is to return the whole page.

In the current version, the **id**, **class** and **code** parameters are optional. In the next release slated for November 2019, the **tag** parameter will also be optional. So you will be able to, for example, just specify the **id** and it will find try to find a match regardless of the tag.

Best regards,

Michael
