### ISSUE TITLE
Request a course should not be displayed

### ISSUE THREAD

**Issue by jprovasnik** [michael-milette/moodle-filter_filtercodes#96]
My students and teachers are not allowed to "request a course" yet this link displays when i use the following code: 
{ifloggedin}
My Courses
{mycoursesmenu}
{/ifloggedin}

Can that link be disabled?

**Comment by michael-milette** [comment]
Hi @jprovasnik 

It is easy to disable that feature. Just go to:

Site Administration > Courses > Request a Course

Next, uncheck the box for Enable Course Requests and save your change. The link should no longer appear in the menu.

Best regards,

Michael

**Comment by jprovasnik** [comment]
@michael-milette im not looking to disable the feature because I need my managers to use that feature. I just don't want it visible to students or teachers. Right now, the courses Filter displays the request a course link to all users, not just those with the permission to request a course. I'm looking to not have the link at all and continue to have my managers request a course through the regular Moodle interface. Is that a possibility with the mycourses filter?

**Comment by jprovasnik** [comment]
FYI - I did a temporary fix that works for my case - I just hid the last item in that dropdown:
li.dropdown.nav-item.show:last-of-type .dropdown-menu.show a:last-of-type {display: none;}

**Comment by michael-milette** [comment]
@jprovasnik , how do you hide the button at the bottom of the All Courses page from your students and teachers?

**Comment by jprovasnik** [comment]
The link is controlled by the permission "moodle/course:request" so my student, teacher, and authenticated user roles do not see that link. I just upgraded to Moodle 3.7 so maybe it's a 3.7 issue?

**Comment by michael-milette** [comment]
Hi @jprovasnik 
It is not a 3.7 issue. My code is currently just checking the Enable Course Request setting.
Thank you for your suggestion.

**Comment by michael-milette** [comment]
HI @jprovasnik,

You asked for it you got it! I added a check for the capability as requested. However, until the next release, that functionality is only included in the version available here on GitHub.

Could you give it a try and let me know if it works as expected?

If it does, I will include the fix in the next official release of FilterCodes which is expected be released on Moodle.org just before the launch of Moodle 3.9 LTS in May 2020.

I would appreciated it if you would please get back to me on this to let me know either way.

Best regards,

Michael

**Comment by jprovasnik** [comment]
Thanks -- I'm on a hosted Moodle environment. i'll pass this along to my host to see if they can vet it in my sandbox.

**Comment by michael-milette** [comment]
Hi @jprovasnik , you may also be interested in #99. Your feedback on the idea would be appreciated.

**Comment by michael-milette** [comment]
Hi @jprovasnik 

Because I know that you use this feature,  I wanted to let you know about some upcoming change to the {mycoursesmenu} tag:

1. The Request a Course link is no longer part of the course list. The functionality is still there but you will need to add a {courserequestmenu} tag right after the  {mycoursesmenu} tag. Alternatively, there is also a new {courserequestmenu0} tag in case you need a top level custom menu link. These changes are already available in the version of FilterCodes here on GitHub and will be included in the release on Moodle.org in May 2021.

2. You may be interested in keeping an eye on #114 . It is currently under development and I am hoping it will be ready in time for the upcoming release.

Best regards,

Michael
