### ISSUE TITLE
Additional HTML Usage

### ISSUE THREAD

**Issue by dcahail** [michael-milette/moodle-filter_filtercodes#98]
I am trying to use this within some html that exists on all pages from the additional HTML block under Appearance. We launch a modal from the footer and have a need to get the {fullname} abd {email} using your filter. No matter how many different ways I try I am unable to get any of the filters to work from this place. It works great if I create a block, but that then won't be available on every page in the Moodle system.

**Comment by michael-milette** [comment]
Hi @dcahail ,

If you can get the tags to work elsewhere, loke in a page, then it is likely that the additional HTML field you are using is not processed through Moodle filters. You should contact the developer of the theme and ask them to add that. They will need to make use of the output functions called format_text(). You can even send them the following link:
https://docs.moodle.org/dev/Output_functions

Best regards,

Michael

**Comment by dcahail** [comment]
Michael,

I appreciate the fast reply, but the additional html under appearance is part of the Moodle core and has been since 2.0. Moodle said contact the author of the filter plugin. So something is amiss. I have been using and writing Moodle plugins since 1.9. I manage over 30 individual Moodle instances for a university and many state agencies.

Any help you can supply is appreciated.

Darrell

**Comment by michael-milette** [comment]
Hi @dcahail ,

As you indicated, the Additional HTML fields are indeed part of Moodle core.

However, FilterCodes doesn't interact with anything but the functions I mentioned in my previous message. You would need to add some code to your theme to override the $OUTPUT->standard_end_of_body_html() renderer so that it passes the content of the additionalhtmlfooter field. As far as I know, filters don't have the ability to extend renderers. It has to be done in the theme.

Hence why I suggested you contact the maintainer of your theme. If you are using one of the core themes, then it would definitely be a core issue.

I wish that filters were applied to those fields. I don't know who told you they are but you can check the source code of lib/outputrenderers.php yourself. Look for the function called standard_end_of_body_html(). There is no filtering function being applied. Just straight out $CFG->additionalhtmlfooter. Ideally, that is exactly where it should be fixed so that support is available in all themes, not just yours or mine. If your buddy can show you where core code passes this field's content through a Moodle filter function, please share.

I might be able to come up with other suggestions but one way or another, they would likely all involve modifying Moodle core or your theme. This is what I have been doing when I develop themes.

With your extensive experience in Moodle development, if you have any other suggestions, please feel free to share.

Best regards,

Michael

**Comment by michael-milette** [comment]
If you don't want to override the renderer, you could do the following instead:

1. Temporarily save the content of $CFG->additionalhtmlfooter.
2. Pass $CFG->additionalhtmlfooter through one of the Moodle functions.
3. Make the call to $OUTPUT->standard_end_of_body_html().
4. Restore the original content of $CFG->additionalhtmlfooter.

That way, it is less likely that you will need to maintain the whole renderer code in your theme should it evolve down the road.

**Comment by dcahail** [comment]
Michael,

Thanks. I am using the base Boost theme that is now part of the Moodle 3.8 core. I am looking at doing your suggestion. I could probably do this using php tags in the additional html block. I have already wrote to Moodle Support and asked about making changes that would allow support of using filters from all of the themes in 3.8+. So far no response but it usually takes 24-48 hours for them to respond.

Thanks again.
Darrell

**Comment by michael-milette** [comment]
I am closing this issue as I have not heard back from you in over a couple of weeks. Please let me know if you need to re-open this issue.
